name: unidad_educatica_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1                # Para consumir APIs REST
  flutter_secure_storage: ^10.0.0-beta.4  # Para guardar el token JWT
  jwt_decoder: ^2.0.1        # Para decodificar token JWT
  provider: ^6.1.2           # Estado global (opcional, puedes usar Riverpod también)
  go_router: ^13.0.0         # Navegación basada en rutas
  fl_chart: ^0.66.0
  json_annotation: ^4.9.0    # Para modelos JSON
  image_picker: ^1.0.4
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6        # Necesario si usas json_serializable
  json_serializable: ^6.7.1   # Para convertir objetos a JSON fácilmente

flutter:
  uses-material-design: true

