services:
  postgres:
    image: postgres:15
    container_name: unidadeducativa_db
    restart: always
    environment:
      POSTGRES_DB: unidad_educativa4
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-network

  springboot-app:
    build: .
    container_name: unidadeducativa_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/unidad_educativa4
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - spring-network

volumes:
  postgres_data:


networks:
  spring-network:
    driver: bridge
